### ISSUE TITLE
2 bugs regarding .getSkin() function

### ISSUE THREAD

**Issue by OtakuGamerAds** [mchorse/mappet#12]
1-
If I die, weird pink black skin comes with the function `.getSkin()`, when I'm morphed to something with the function `.getSkin()`
This can be fixed by relaunching the game. 
![image](https://user-images.githubusercontent.com/43914433/147382648-8673c49d-e6bc-458f-835d-f0393b89de2b.png)

2-
Most of the time, if I just close the world and rejoin, I become Alex's skin, when I'm morphed to something with the function `.getSkin()`, until relaunching.

**Comment by mchorse** [comment]
Thanks for the report, however, I'm writing this for transparency, I'll deal with it whenever I'll have motivation to deal with it, or even possibly never. There is a reason why I quit my Discord servers, to keep distance from stuff that distract me from my current objective (which not a lot of people seem to be interested in right now).
