### ISSUE TITLE
Request/suggestion

### ISSUE THREAD

**Issue by TheSexyYeti** [mchorse/mappet#14]
Not really a bug as it is a feature request/suggestion. The NPCs for mappet are some of the best I've seen. I personally like them better then the Custom NPCs mod. And I was wondering if there was a way to let you make NPC's that spawn naturally in the world like normal mobs do?. With spawn chance, spawn conditions (night/day, biome etc.), loot drops. It would be cool if they could spawn with dialog options too.

**Comment by mchorse** [comment]
That would be cool indeed, however as the read me states. I no longer support my mods (as in quitting modding).
