### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by PyXiion** [mchorse/mappet#19]
Hello! Will classes be implemented in scripts? As far as I understand, the Nashorn library is outdated and is not being updated. Or I downloaded the old version :thinking:

**Comment by mchorse** [comment]
Nashorn doesn’t support ES6. In theory, maybe it’s possible to add transpiler ES6 -> ES5 (like Babel), but I no longer developing this mod (or any of my mods), so it’s very unlikely it will be added.
